### ISSUE TITLE
project todo

### ISSUE THREAD

**Issue by alexalannunes** [alexalannunes/react-todo-firebase#1]
- [x] change `package.json` `homepage: "."`
- [x] configure hosting
- [x] configure simple route
- [x] configure auth
- [x] configure database (firestore)
- [x] configure storage
